---
title: "qrmr_example"
author: "Brandon Sie"
date: "10/01/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
options(stringsAsFactors = FALSE)
`%>%` <- magrittr::`%>%`
library(ggplot2)

```



```{r, read}
# Read plink quantile regression output.
qr_output <- data.table::fread("example_input_data/qr_ht_example.tsv", data.table = FALSE)

# Exclude variants that failed quantile regression. -9 is default NA value
qr_subset <- qr_output[qr_output$tau1 != -9,]

```

```{r, mr}

#' mr_fun Function to call to run meta regression on plink quantile regression data
#' @param input_row information for one variant from plink quantile regression
#' @param rma_method metafor parameter
#' @param tau_index positions in input_row corresponding to quantile values
#' @param beta_index positions in input_row corresponding to quantile regression beta values
#' @param se_index positions in input_row corresponding to quantile regression standard error values

mr_fun <- function(input_row, rma_method = "EB", tau_index = 5:9, 
                   beta_index = c(11,19,27,35,43),
                   se_index = c(13,21,29,37,45)){
  
  # format data for input to metafor::rma
  snp_df <- data.frame(
    tau = input_row[tau_index] %>% as.numeric,
    snp_beta = input_row[beta_index] %>% as.numeric,
    snp_se = input_row[se_index] %>% as.numeric
  )
  snp_df$tau2 <- (snp_df$tau-0.5)^2
  
  snp_rma <- try(
    metafor::rma(
      yi = snp_beta, sei = snp_se,
      mods = cbind(tau, tau2),
      data = snp_df,
      method = rma_method 
    ) 
  )
  # error handing
  if(class(snp_rma)[1] == "try-error"){
    mr_output <- rep(-9, 12)
  } else{
    mr_output <- c(snp_rma$beta, snp_rma$ci.lb, snp_rma$ci.ub, snp_rma$pval)
  }
  
  names(mr_output) <- c(
    "MR_b0", "MR_b1", "MR_b2","MR_b0_L95", "MR_b1_L95", "MR_b2_L95","MR_b0_U95",
    "MR_b1_U95", "MR_b2_U95","MR_b0_pval", "MR_b1_pval", "MR_b2_pval")

  return(mr_output)
}
  

# Run meta regression
future::plan(future::multisession, workers = future::availableCores("") - 1)
mr_out <- future.apply::future_apply(qr_subset, 1, mr_fun) 

# Format meta regression output table
mr_out_df <- mr_out %>% t %>% as.data.frame

# join quantile regression input data and meta regression data
qrmr_df <- dplyr::bind_cols(qr_subset, mr_out_df)
qrmr_sub <- qrmr_df[qrmr_df$MR_b0 != -9,]


```



```{r pval}
# process meta regression p values
qrmr_sub_pval <- qrmr_sub[,grep("pval", colnames(qrmr_sub))]
qrmr_sub$min_pval <- qrmr_sub_pval %>% apply(1, min)
qrmr_sub$min_pval_2 <- qrmr_sub_pval[,-1] %>% apply(1,min)
qrmr_sub$log10_min_pval <- qrmr_sub$min_pval %>% log10 * -1
qrmr_sub$log10_min_pval_2 <- qrmr_sub$min_pval_2 %>% log10 * -1

# subset variants by pvalue threshold  
pval_thresh <- 0.05/(nrow(qrmr_sub)*3)
qrmr_filter <- qrmr_sub[qrmr_sub$min_pval < pval_thresh,]
  
```

